-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 21:54:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia` ;

-- -----------------------------------------------------
-- Table `db_farmacia`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_farmacia`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_farmacia`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_farmacia`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_farmacia`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `db_farmacia`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` INT NOT NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`fk_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `db_farmacia`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- SELECT * FROM db_farmacia.tb_categoria;

-- SELECT * FROM db_farmacia.tb_produto;

INSERT INTO `db_farmacia`.`tb_produto` (`nome`, `preco`, `fk_categoria`) VALUES ('resprin', '15', '1');
INSERT INTO `db_farmacia`.`tb_produto` (`nome`, `preco`, `fk_categoria`) VALUES ('batom', '20', '2');
INSERT INTO `db_farmacia`.`tb_produto` (`nome`, `preco`, `fk_categoria`) VALUES ('shampoo', '50', '3');

-- SELECT * FROM tb_produto WHERE	preco > 20

-- SELECT * FROM tb_produto WHERE preco BETWEEN 18 AND 50 

-- SELECT * FROM tb_produto WHERE nome LIKE 'b%'

-- select * FROM tb_produto INNER JOIN	tb_categoria ON tb_produto.fk_categoria = tb_categoria.id_categoria WHERE tb_categoria.tipo = "remedio"