-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 22:40:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_game_online` ;

-- -----------------------------------------------------
-- Table `db_game_online`.`tb_classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_game_online`.`tb_classe` ;

CREATE TABLE IF NOT EXISTS `db_game_online`.`tb_classe` (
  `idtb_classe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idtb_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_game_online`.`tb_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_game_online`.`tb_personagem` ;

CREATE TABLE IF NOT EXISTS `db_game_online`.`tb_personagem` (
  `idtb_personagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `forca` VARCHAR(45) NOT NULL,
  `defesa` VARCHAR(45) NOT NULL,
  `fk_personagem` INT NOT NULL,
  PRIMARY KEY (`idtb_personagem`),
  INDEX `fk_tb_personagem_tb_classe_idx` (`fk_personagem` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`fk_personagem`)
    REFERENCES `db_game_online`.`tb_classe` (`idtb_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- SELECT * FROM tb_classe

INSERT INTO `db_game_online`.`tb_classe` (`nome`, `tipo`) VALUES ('guerrio', 'cor a cor');
INSERT INTO `db_game_online`.`tb_classe` (`nome`, `tipo`) VALUES ('arqueiro', 'distancia');
INSERT INTO `db_game_online`.`tb_classe` (`nome`, `tipo`) VALUES ('mago', 'distancia');

-- SELECT * FROM tb_personagem 

INSERT INTO `db_game_online`.`tb_personagem` (`nome`, `sexo`, `forca`, `defesa`, `fk_personagem`) VALUES ('Marcia', 'M', '2000', '2000', '1');
INSERT INTO `db_game_online`.`tb_personagem` (`nome`, `sexo`, `forca`, `defesa`, `fk_personagem`) VALUES ('Pedro', 'M', '1000', '3000', '2');
INSERT INTO `db_game_online`.`tb_personagem` (`nome`, `sexo`, `forca`, `defesa`, `fk_personagem`) VALUES ('Kevelly', 'F', '3000', '3000', '3');

-- select * from tb_personagem where forca > 2000

-- select * from tb_personagem where defesa between 1000 and 3000

-- select * from tb_personagem where tb_personagem.nome like '%M'

 -- SELECT * FROM tb_personagem INNER JOIN tb_classe ON tb_personagem.fk_personagem = tb_classe.idtb_classe
 
 -- SELECT * FROM tb_personagem INNER JOIN tb_classe ON tb_personagem.fk_personagem = tb_classe.idtb_classe where tb_classe.nome = "arqueiro"





