-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 22:10:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria` ;

-- -----------------------------------------------------
-- Table `db_pizzaria`.`tb_pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pizzaria`.`tb_pizza` ;

CREATE TABLE IF NOT EXISTS `db_pizzaria`.`tb_pizza` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pizzaria`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_pizzaria`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `massa` VARCHAR(45) NOT NULL,
  `borda` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `fk_pizza` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_tb_categoria_tb_pizza_idx` (`fk_pizza` ASC) VISIBLE,
  CONSTRAINT `fk_tb_categoria_tb_pizza`
    FOREIGN KEY (`fk_pizza`)
    REFERENCES `db_pizzaria`.`tb_pizza` (`id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- SELECT * FROM db_pizzaria.tb_categoria;

INSERT INTO `db_pizzaria`.`tb_categoria` (`massa`, `borda`, `tamanho`, `fk_pizza`) VALUES ('grossa', 'catupiry', 'grande', '1');
INSERT INTO `db_pizzaria`.`tb_categoria` (`massa`, `borda`, `tamanho`, `fk_pizza`) VALUES ('media', 'cheddar', 'media', '2');
INSERT INTO `db_pizzaria`.`tb_categoria` (`massa`, `borda`, `tamanho`, `fk_pizza`) VALUES ('fina', 'chocolate', 'pequena', '3');

-- SELECT * FROM db_pizzaria.tb_pizza;

INSERT INTO `db_pizzaria`.`tb_pizza` (`nome`, `preco`) VALUES ('calabresa', '10');
INSERT INTO `db_pizzaria`.`tb_pizza` (`nome`, `preco`) VALUES ('mussarela', '10');
INSERT INTO `db_pizzaria`.`tb_pizza` (`nome`, `preco`) VALUES ('portuguesa', '20');

-- select * from tb_pizza where preco > 10

-- select * from tb_pizza where preco between 10 and 15

-- SELECT * FROM tb_pizza WHERE nome LIKE 'c%'

-- SELECT * FROM tb_categoria INNER JOIN tb_pizza ON tb_categoria.fk_pizza = tb_categoria.id_categoria
  
-- SELECT * FROM tb_categoria INNER JOIN tb_pizza ON tb_categoria.fk_pizza = tb_categoria.id_categoria WHERE tb_pizza.nome = "portuguesa"

 
  -- SELECT * FROM tb_personagem INNER JOIN tb_classe ON tb_personagem.fk_personagem = tb_classe.idtb_classe